CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

SET timezone = 'UTC';

GRANT ALL PRIVILEGES ON DATABASE diapro_db TO diapro_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO diapro_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO diapro_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO diapro_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO diapro_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO diapro_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO diapro_user; 